version = 0.1
[default.deploy.parameters]
stack_name = "labs-backend"
resolve_s3 = true
s3_prefix = "labs-backend"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
